apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preprovisioned-smb-vhdx-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-vhdx-for-windows-rwx
  volumeName: preprovisioned-smb-vhdx
  resources:
    requests:
      storage: 100Gi
