apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preprovisioned-smb-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-for-windows-rwx
  resources:
    requests:
      storage: 100Gi
  volumeName: preprovisioned-smb
