apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: apps
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: iscsi-for-windows-rwo
  resources:
    requests:
      storage: 200Gi
