apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-driver-iscsi-for-windows.fullname" . }}-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "csi-driver-iscsi-for-windows.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver-iscsi-for-windows.controllerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
