{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-driver-iscsi-for-windows.controllerServiceAccountName" . }}
  labels:
    {{- include "csi-driver-iscsi-for-windows.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.controller.serviceAccount.automount }}
{{- end }}
