apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-smb-vhdx-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-vhdx-for-windows-rwx
  resources:
    requests:
      storage: 1Gi
