apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-nodeonly-smb-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: static-nodeonly-smb
