apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-smb-vhdx-restore
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-vhdx-for-windows-rwx
  dataSource:
    name: shared-smb-vhdx-snap-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  resources:
    requests:
      storage: 100Gi
