apiVersion: v1
kind: PersistentVolume
metadata:
  name: preprovisioned-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-for-windows-rwx
  csi:
    driver: windows-storage.csi.windows.microsoft.com
    volumeHandle: "nfs://win-storage.lab.local/preprovisioned-nfs?name=preprovisioned-nfs&shareBackend=directory&sharePath=E%3A%5CNfsShares%5Cpreprovisioned-nfs&vhdxPath=E%3A%5CNfsShares%5Cpreprovisioned-nfs&capacityBytes=1073741824"
    volumeAttributes: {}
