apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preprovisioned-nfs-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-for-windows-rwx
  resources:
    requests:
      storage: 1Gi
  volumeName: preprovisioned-nfs
