apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-for-windows-rwx
provisioner: smb.csi.windows.microsoft.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  shareParentPath: "E:\\SmbShares"
  smbServer: "win-storage.lab.local"
  smbChangeAccess: "Everyone"
