---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-windows-storage-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-windows-storage-controller
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments", "csinodes", "csidrivers", "csistoragecapacities"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-windows-storage-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-windows-storage-controller
subjects:
  - kind: ServiceAccount
    name: csi-windows-storage-controller
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-iscsi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-iscsi-controller
  template:
    metadata:
      labels:
        app: csi-iscsi-controller
    spec:
      serviceAccountName: csi-windows-storage-controller
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.4.2
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.10.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=29752
            - --v=2
          ports:
            - containerPort: 29752
              name: healthz
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: iscsi
          image: ghcr.io/taliesins/csi-driver-for-windows-storage-server:0.2.0
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --mode=controller
            - --drivername=iscsi.csi.windows.microsoft.com
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: WINRM_HOST
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_HOST
            - name: WINRM_PORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PORT
                  optional: true
            - name: WINRM_TLS
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TLS
                  optional: true
            - name: WINRM_INSECURE
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_INSECURE
                  optional: true
            - name: WINRM_AUTH
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_AUTH
                  optional: true
            - name: WINRM_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TIMEOUT
                  optional: true
            - name: WINRM_PS_IMPORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PS_IMPORT
                  optional: true
            - name: WINRM_USER
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_USER
            - name: WINRM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PASSWORD
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-nfs-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-nfs-controller
  template:
    metadata:
      labels:
        app: csi-nfs-controller
    spec:
      serviceAccountName: csi-windows-storage-controller
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.10.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=29752
            - --v=2
          ports:
            - containerPort: 29752
              name: healthz
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: nfs
          image: ghcr.io/taliesins/csi-driver-for-windows-storage-server:0.2.0
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --mode=controller
            - --drivername=nfs.csi.windows.microsoft.com
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: WINRM_HOST
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_HOST
            - name: WINRM_PORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PORT
                  optional: true
            - name: WINRM_TLS
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TLS
                  optional: true
            - name: WINRM_INSECURE
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_INSECURE
                  optional: true
            - name: WINRM_AUTH
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_AUTH
                  optional: true
            - name: WINRM_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TIMEOUT
                  optional: true
            - name: WINRM_PS_IMPORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PS_IMPORT
                  optional: true
            - name: WINRM_USER
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_USER
            - name: WINRM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PASSWORD
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-nfs-vhdx-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-nfs-vhdx-controller
  template:
    metadata:
      labels:
        app: csi-nfs-vhdx-controller
    spec:
      serviceAccountName: csi-windows-storage-controller
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.10.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=29752
            - --v=2
          ports:
            - containerPort: 29752
              name: healthz
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: nfs-vhdx
          image: ghcr.io/taliesins/csi-driver-for-windows-storage-server:0.2.0
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --mode=controller
            - --drivername=nfs-vhdx.csi.windows.microsoft.com
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: WINRM_HOST
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_HOST
            - name: WINRM_PORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PORT
                  optional: true
            - name: WINRM_TLS
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TLS
                  optional: true
            - name: WINRM_INSECURE
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_INSECURE
                  optional: true
            - name: WINRM_AUTH
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_AUTH
                  optional: true
            - name: WINRM_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TIMEOUT
                  optional: true
            - name: WINRM_PS_IMPORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PS_IMPORT
                  optional: true
            - name: WINRM_USER
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_USER
            - name: WINRM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PASSWORD
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-smb-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-smb-controller
  template:
    metadata:
      labels:
        app: csi-smb-controller
    spec:
      serviceAccountName: csi-windows-storage-controller
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.10.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=29752
            - --v=2
          ports:
            - containerPort: 29752
              name: healthz
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: smb
          image: ghcr.io/taliesins/csi-driver-for-windows-storage-server:0.2.0
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --mode=controller
            - --drivername=smb.csi.windows.microsoft.com
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: WINRM_HOST
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_HOST
            - name: WINRM_PORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PORT
                  optional: true
            - name: WINRM_TLS
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TLS
                  optional: true
            - name: WINRM_INSECURE
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_INSECURE
                  optional: true
            - name: WINRM_AUTH
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_AUTH
                  optional: true
            - name: WINRM_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TIMEOUT
                  optional: true
            - name: WINRM_PS_IMPORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PS_IMPORT
                  optional: true
            - name: WINRM_USER
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_USER
            - name: WINRM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PASSWORD
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-smb-vhdx-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-smb-vhdx-controller
  template:
    metadata:
      labels:
        app: csi-smb-vhdx-controller
    spec:
      serviceAccountName: csi-windows-storage-controller
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.10.0
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=29752
            - --v=2
          ports:
            - containerPort: 29752
              name: healthz
              protocol: TCP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: smb-vhdx
          image: ghcr.io/taliesins/csi-driver-for-windows-storage-server:0.2.0
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --mode=controller
            - --drivername=smb-vhdx.csi.windows.microsoft.com
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: WINRM_HOST
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_HOST
            - name: WINRM_PORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PORT
                  optional: true
            - name: WINRM_TLS
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TLS
                  optional: true
            - name: WINRM_INSECURE
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_INSECURE
                  optional: true
            - name: WINRM_AUTH
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_AUTH
                  optional: true
            - name: WINRM_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TIMEOUT
                  optional: true
            - name: WINRM_PS_IMPORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PS_IMPORT
                  optional: true
            - name: WINRM_USER
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_USER
            - name: WINRM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PASSWORD
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
