---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-windows-storage-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-windows-storage-controller
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims", "events"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumes/finalizers"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["nodes", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments", "csinodes", "csidrivers", "csistoragecapacities"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/finalizers"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-windows-storage-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-windows-storage-controller
subjects:
  - kind: ServiceAccount
    name: csi-windows-storage-controller
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-windows-storage-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-windows-storage-controller
  template:
    metadata:
      labels:
        app: csi-windows-storage-controller
    spec:
      serviceAccountName: csi-windows-storage-controller
      containers:
        - name: windows-storage
          image: ghcr.io/taliesins/csi-driver-for-windows-storage-server:0.2.0
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --mode=controller
            - --drivername=windows-storage.csi.windows.microsoft.com
            - --kubernetes-integration=true
            - --controller-publish=true
            - --liveness-port=29752
            - --v=5
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: WINRM_HOST
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_HOST
            - name: WINRM_PORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PORT
                  optional: true
            - name: WINRM_TLS
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TLS
                  optional: true
            - name: WINRM_INSECURE
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_INSECURE
                  optional: true
            - name: WINRM_AUTH
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_AUTH
                  optional: true
            - name: WINRM_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_TIMEOUT
                  optional: true
            - name: WINRM_PS_IMPORT
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PS_IMPORT
                  optional: true
            - name: WINRM_USER
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_USER
            - name: WINRM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csi-driver-winrm
                  key: WINRM_PASSWORD
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - containerPort: 29752
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
      volumes:
        - name: socket-dir
          emptyDir: {}
