apiVersion: v1
kind: PersistentVolume
metadata:
  name: preprovisioned-vhdx
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-for-windows-rwo
  csi:
    driver: iscsi.csi.windows.microsoft.com
    volumeHandle: "REPLACE_WITH_VOLUME_ID" # base64-encoded ID from your controller
    fsType: xfs                            # optional; ext4/xfs supported
    volumeAttributes: {}                   # optional; leave empty or omit entirely
