apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preprovisioned-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-for-windows-rwo
  resources:
    requests:
      storage: 100Gi
  volumeName: preprovisioned-vhdx
