apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-nodeonly-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: nfs.csi.windows.microsoft.com
    volumeHandle: "static-nodeonly-nfs"
    volumeAttributes:
      protocol: "nfs"
      nfsServer: "win-storage.lab.local"
      nfsExportPath: "/static-nodeonly-nfs"
      nfsVersion: "4.1"
