apiVersion: v1
kind: PersistentVolume
metadata:
  name: preprovisioned-iscsi
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-for-windows-rwo
  csi:
    driver: iscsi.csi.windows.microsoft.com
    volumeHandle: "iscsi://win-storage.lab.local:3260/iqn.1991-05.com.microsoft:win-storage-preprovisioned-iscsi/lun/0?name=preprovisioned-iscsi&targetName=preprovisioned-iscsi&vhdxPath=E%3A%5CiSCSIVirtualDisks%5Cpreprovisioned-iscsi.vhdx&capacityBytes=107374182400"
    fsType: xfs
    volumeAttributes: {}
