apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "csi-driver-for-windows-storage-server.fullname" . }}-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "csi-driver-for-windows-storage-server.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-driver-for-windows-storage-server.controllerServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
