apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "csi-driver-for-windows-storage-server.controllerName" . }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims", "nodes", "events", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments", "csinodes", "csidrivers", "csistoragecapacities"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
