{{- $root := . -}}
{{- $key := "windows-storage" -}}
{{- $driver := mergeOverwrite (include "csi-driver-for-windows-storage-server.driverDefaults" . | fromYaml) (get (.Values.drivers | default dict) $key | default dict) -}}
{{- if $driver.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ $driver.name }}
spec:
  attachRequired: {{ and (not $root.Values.nodeOnly) $driver.attachRequired }}
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
{{- end }}
