{{- $root := . -}}
{{- range $key, $driver := .Values.drivers }}
{{- if $driver.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ $driver.name }}
spec:
  attachRequired: {{ and (not $root.Values.nodeOnly) $driver.attachRequired }}
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
{{- end }}
{{- end }}
