{{- $root := . -}}
{{- $key := "windows-storage" -}}
{{- $driver := get .Values.drivers $key | default (dict "enabled" true "name" "windows-storage.csi.windows.microsoft.com" "attachRequired" true "needsIscsi" true "livenessPort" 29753) -}}
{{- if $driver.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ $driver.name }}
spec:
  attachRequired: {{ and (not $root.Values.nodeOnly) $driver.attachRequired }}
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
{{- end }}
