apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "csi-driver-for-windows-storage-server.fullname" . }}-node
  labels:
    {{- include "csi-driver-for-windows-storage-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "csi-driver-for-windows-storage-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csi-driver-for-windows-storage-server.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "csi-driver-for-windows-storage-server.nodeServiceAccountName" . }}
      containers:
        - name: node-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(KUBE_NODE_NAME)
          env:
            - name: CSI_ENDPOINT
              value: "unix:///csi/csi.sock"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-driver-for-windows-storage-server
            type: DirectoryOrCreate
