apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csi-driver-for-windows-storage-server.controllerName" . }}
  labels:
    {{- include "csi-driver-for-windows-storage-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "csi-driver-for-windows-storage-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csi-driver-for-windows-storage-server.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "csi-driver-for-windows-storage-server.controllerServiceAccountName" . }}
      containers:
        - name: controller-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --mode=controller
            {{- if gt (int .Values.controller.replicas) 1 }}
            - --leader-election=true
            - --leader-election-name={{ include "csi-driver-for-windows-storage-server.controllerName" . }}
            - --leader-election-namespace=$(POD_NAMESPACE)
            - --leader-election-identity=$(POD_NAME)
            - --leader-election-lease-duration={{ .Values.controller.leaderElection.leaseDuration }}
            - --leader-election-renew-deadline={{ .Values.controller.leaderElection.renewDeadline }}
            - --leader-election-retry-period={{ .Values.controller.leaderElection.retryPeriod }}
            {{- end }}
          env:
            - name: CSI_ENDPOINT
              value: "unix:///csi/csi.sock"
            {{- if gt (int .Values.controller.replicas) 1 }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- end }}
            {{- include "csi-driver-for-windows-storage-server.winrmEnv" . | nindent 12 }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-driver-for-windows-storage-server
            type: DirectoryOrCreate
