apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csi-driver-for-windows-storage-server.controllerName" . }}
  labels:
    {{- include "csi-driver-for-windows-storage-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "csi-driver-for-windows-storage-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csi-driver-for-windows-storage-server.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "csi-driver-for-windows-storage-server.controllerServiceAccountName" . }}
      containers:
        - name: controller-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --endpoint=$(CSI_ENDPOINT)
          env:
            - name: CSI_ENDPOINT
              value: "unix:///csi/csi.sock"
            - name: WINRM_HOST
              value: {{ required "winrm.host is required" .Values.winrm.host | quote }}
            - name: WINRM_PORT
              value: {{ .Values.winrm.port | quote }}
            - name: WINRM_TLS
              value: {{ .Values.winrm.tls | quote }}
            - name: WINRM_INSECURE
              value: {{ .Values.winrm.insecure | quote }}
            - name: WINRM_AUTH
              value: {{ .Values.winrm.auth | quote }}
            - name: WINRM_TIMEOUT
              value: {{ .Values.winrm.timeout | quote }}
            {{- if .Values.winrm.psImport }}
            - name: WINRM_PS_IMPORT
              value: {{ .Values.winrm.psImport | quote }}
            {{- end }}
            - name: WINRM_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "csi-driver-for-windows-storage-server.winrmSecretName" . }}
                  key: WINRM_USER
            - name: WINRM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "csi-driver-for-windows-storage-server.winrmSecretName" . }}
                  key: WINRM_PASSWORD
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-driver-for-windows-storage-server
            type: DirectoryOrCreate
