# Controller-specific ServiceAccount
nodeOnly: false

controller:
  replicas: 1
  leaderElection:
    leaseDuration: 15s
    renewDeadline: 10s
    retryPeriod: 2s
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

# Node-specific ServiceAccount
node:
  initiatorNamePath: /etc/iscsi/initiatorname.iscsi
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

drivers:
  windows-storage:
    enabled: true
    name: windows-storage.csi.windows.microsoft.com
    attachRequired: true
    needsIscsi: true
    livenessPort: 29753

sidecars:
  logLevel: 2
  provisioner:
    image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
  attacher:
    image: registry.k8s.io/sig-storage/csi-attacher:v4.4.2
  nodeDriverRegistrar:
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
  livenessProbe:
    image: registry.k8s.io/sig-storage/livenessprobe:v2.10.0

# Default values for csi-driver-for-windows-storage-server
image:
  repository: ghcr.io/taliesins/csi-driver-for-windows-storage-server
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

# If you need to pull images from a private registry, set this
imagePullSecrets: []

winrm:
  host: ""
  port: 5986
  tls: true
  insecure: true
  auth: basic
  timeout: 60s
  psImport: ""

  # Use an existing Secret with WINRM_USER and WINRM_PASSWORD keys.
  existingSecret: ""

  # When existingSecret is empty, the chart creates a Secret using winrm.user and winrm.password.
  user: ""
  password: ""
