apiVersion: v1
kind: Secret
metadata:
  name: static-smb-vhdx-credentials
  namespace: apps
type: Opaque
stringData:
  smbUsername: "REPLACE_WITH_USERNAME"
  smbPassword: "REPLACE_WITH_PASSWORD"
  smbDomain: "REPLACE_WITH_DOMAIN"
