package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestResolveNodeID(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "initiatorname.iscsi")
	require.NoError(t, os.WriteFile(path, []byte("InitiatorName=iqn.1993-08.org.debian:01:node-a\n"), 0o600))

	got, err := resolveNodeID(" explicit-node ", path)
	require.NoError(t, err)
	assert.Equal(t, "explicit-node", got)

	got, err = resolveNodeID("", path)
	require.NoError(t, err)
	assert.Equal(t, "iqn.1993-08.org.debian:01:node-a", got)
}

func TestParseNodeIDContent(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    string
	}{
		{
			name:    "initiator name file",
			content: "# generated by open-iscsi\nInitiatorName=iqn.1993-08.org.debian:01:node-a\n",
			want:    "iqn.1993-08.org.debian:01:node-a",
		},
		{
			name:    "raw node id",
			content: "iqn.1993-08.org.debian:01:node-b\n",
			want:    "iqn.1993-08.org.debian:01:node-b",
		},
		{
			name:    "quoted value",
			content: "NodeID='iqn.1993-08.org.debian:01:node-c'\n",
			want:    "iqn.1993-08.org.debian:01:node-c",
		},
		{
			name:    "unsupported keys ignored",
			content: "Other=value\nInitiatorName=iqn.1993-08.org.debian:01:node-d\n",
			want:    "iqn.1993-08.org.debian:01:node-d",
		},
		{
			name:    "empty",
			content: "\n# comment\n",
			want:    "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, parseNodeIDContent(tt.content))
		})
	}
}
